# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "de6cd64758fb452c8827cff441b7e97c"
name = "pod-artwork-checker-1"
application_url = "https://pod-artwork-checker.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://pod-artwork-checker.onrender.com/auth/callback" ]
